---
title: 'Data Wrangling Exercice1  :  Basic Data Manipulation'
author: "Frederic TWAHIRWA."
date: "1 février 2017"
output: html_document
---

## Introduction 

In this exercise, we  work with a toy data set showing product purchases from an electronics store. While the data set is small and simple, it still illustrates many of the challenges we have to address in real-world data wrangling

```{r}
# load packages
library(dplyr)
library(tidyr)
```

```{r}
# load dat set in tamporaly data set "refine"
refine<-read.table('refine_original.csv', header = T,sep=';')
```

```{r}
#clean up name by using lapply and tolower function 

refine$company<-lapply(refine$company,tolower)
unique(refine$company)

refine$company<-gsub(".*s", "philips",refine$company)
refine$company<-gsub(".*r", "unilever",refine$company)
refine$company<-gsub("ak.*", "akzo",refine$company)

# separate product code and number
refine<-separate(refine, Product.code...number, c("product_code", "product_number"), sep="-")
```

```{r}
##add producct categorie
# 1st create a new column "product_categorie"

refine<-refine %>% 
        mutate(product_categorie = product_code)

# 2nd reognise the data frame 
refine<-refine [c(1, 8, 2, 3 ,4, 5, 6, 7)]

# 3rd affect product categories , I am using gsub 
# I have tried to use 'dplyr' with mutate and conditional statement, but I found it more complicated and no readble

refine$product_categorie<-gsub("p","Smartphone", refine$product_categorie)
refine$product_categorie<-gsub("v","TV", refine$product_categorie)
refine$product_categorie<-gsub("x","Laptop", refine$product_categorie)
refine$product_categorie<-gsub("q","Tablet", refine$product_categorie)

```

```{r}

# add full address 
refine<-refine %>%
        unite("full_adress", address, city, country, sep=",")
```

```{r}

# create dummy variable , in this case I am using "dplyr" with mutate, as.numeric allows to coerce the TRUE logic variable in 1 numeric and FALSe logic variable in 0 numeric

refine<-refine %>% 
        mutate(company_philips=as.numeric(company=="philips")) %>% 
        mutate(company_akzo=as.numeric(company=="akzo")) %>% 
        mutate(company_van_houten=as.numeric(company=="van houten")) %>% 
        mutate(company_unilever=as.numeric(company=="unilever"))

refine<-refine %>% 
        mutate(product_smartphone=as.numeric(product_categorie=="Smartphone")) %>% 
        mutate(product_tv=as.numeric(product_categorie=="TV")) %>%
        mutate(product_laptop=as.numeric(product_categorie=="Laptop")) %>%
        mutate(product_tablet=as.numeric(product_categorie=="Tablet")) 
```

```{r}
# write a csv on my working directory

write.csv(refine, file = "refine_clean.csv")
             
```
